### ISSUE TITLE
Update Contributing.md

### ISSUE THREAD

**Issue by lephanthuymai** [UBC-MDS/datascience_eda#5]
Agree upon a collaboration strategy that describes how you will work together on this project (e.g., GitHub flow and edit CONTRIBUTING.md to reflect your strategy. Again, there will be a default version of this file. You can use it as is or adapt it with appropriate attribution. Here are some example CONTRIBUTING.md files for your reference.

Software Carpentry CONTRIBUTING.md
factory_bot_rails CONTRIBUTING.md
moby CONTRIBUTING.md

**Comment by rahulkuriyedath** [comment]
@lephanthuymai There already seems to be 2 files in the repo called `CONDUCT.rst` and `CONTRIBUTING.rst`. So can we close this issue?

**Comment by lephanthuymai** [comment]
Please review those files to see if they meet the requirements of the
milestone.

**Comment by rahulkuriyedath** [comment]
@lephanthuymai The submission instructions say that we may choose to use the default files that are created or edit it if we want. I think we can leave it as is, since it looks fine. 
@adibns @charlessuresh Tagging you guys just FYI.

**Comment by lephanthuymai** [comment]
Hi Rahul,
Please check the links in https://github.com/UBC-MDS/datascience_eda/blob/main/CONTRIBUTING.rst, they won't work.

We are using Github flow (branching), the current CONTRIBUTING file is using forking, the requirement says `Agree upon a collaboration strategy that describes how you will work together on this project (e.g., GitHub flow and edit CONTRIBUTING.md to reflect your strategy`. For new contributors, I agree that we should use forking instead of branching due to the level of trust, but we need to confirm with the instructors if it is ok to have such a difference.

Thanks.
