### ISSUE TITLE
eda_categorical_columns - Write Specification

### ISSUE THREAD

**Issue by lephanthuymai** [UBC-MDS/datascience_eda#8]
For this milestone you will write function documentation that will serve as specifications, but you will NOT write any code for your package functions. Specifically, set-up empty functions (with appropriate function names) containing no code in the files where you will eventually write code. Write function documentation (e.g., complete docstrings). These are the functions you wrote about in your proposal.

TODO: replace Function 2 with an actual function name

**Comment by adibns** [comment]
Changes that are being made:
The function now returns a plot object along with a dataframe

**Comment by adibns** [comment]
Change being made to explore_categorical_columns:
 - Returns a list containing plot objects along with previously returned dataframe
